// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DMEClient is the client API for DME service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DMEClient interface {
	RequestAccess(ctx context.Context, opts ...grpc.CallOption) (DME_RequestAccessClient, error)
}

type dMEClient struct {
	cc grpc.ClientConnInterface
}

func NewDMEClient(cc grpc.ClientConnInterface) DMEClient {
	return &dMEClient{cc}
}

func (c *dMEClient) RequestAccess(ctx context.Context, opts ...grpc.CallOption) (DME_RequestAccessClient, error) {
	stream, err := c.cc.NewStream(ctx, &DME_ServiceDesc.Streams[0], "/proto.DME/RequestAccess", opts...)
	if err != nil {
		return nil, err
	}
	x := &dMERequestAccessClient{stream}
	return x, nil
}

type DME_RequestAccessClient interface {
	Send(*AccesRequest) error
	Recv() (*AccessResponse, error)
	grpc.ClientStream
}

type dMERequestAccessClient struct {
	grpc.ClientStream
}

func (x *dMERequestAccessClient) Send(m *AccesRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dMERequestAccessClient) Recv() (*AccessResponse, error) {
	m := new(AccessResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DMEServer is the server API for DME service.
// All implementations must embed UnimplementedDMEServer
// for forward compatibility
type DMEServer interface {
	RequestAccess(DME_RequestAccessServer) error
	mustEmbedUnimplementedDMEServer()
}

// UnimplementedDMEServer must be embedded to have forward compatible implementations.
type UnimplementedDMEServer struct {
}

func (UnimplementedDMEServer) RequestAccess(DME_RequestAccessServer) error {
	return status.Errorf(codes.Unimplemented, "method RequestAccess not implemented")
}
func (UnimplementedDMEServer) mustEmbedUnimplementedDMEServer() {}

// UnsafeDMEServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DMEServer will
// result in compilation errors.
type UnsafeDMEServer interface {
	mustEmbedUnimplementedDMEServer()
}

func RegisterDMEServer(s grpc.ServiceRegistrar, srv DMEServer) {
	s.RegisterService(&DME_ServiceDesc, srv)
}

func _DME_RequestAccess_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DMEServer).RequestAccess(&dMERequestAccessServer{stream})
}

type DME_RequestAccessServer interface {
	Send(*AccessResponse) error
	Recv() (*AccesRequest, error)
	grpc.ServerStream
}

type dMERequestAccessServer struct {
	grpc.ServerStream
}

func (x *dMERequestAccessServer) Send(m *AccessResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dMERequestAccessServer) Recv() (*AccesRequest, error) {
	m := new(AccesRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DME_ServiceDesc is the grpc.ServiceDesc for DME service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DME_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DME",
	HandlerType: (*DMEServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RequestAccess",
			Handler:       _DME_RequestAccess_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/nodes.proto",
}
